/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FactoryPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/modals/PromiseConfirmModal.ts
var import_obsidian = require("obsidian");
var PromiseConfirmModal = class extends import_obsidian.Modal {
  constructor(app, message) {
    super(app);
    this.message = message;
  }
  resolvePromise = () => void 0;
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("p", { text: this.message });
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Yes").setCta().onClick(() => {
        this.resolvePromise(true);
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("No").onClick(() => {
        this.resolvePromise(false);
        this.close();
      })
    );
  }
  async openAndWait() {
    return new Promise((resolve) => {
      this.resolvePromise = resolve;
      this.open();
    });
  }
  onClose() {
    this.contentEl.empty();
    if (this.resolvePromise) {
      this.resolvePromise(false);
    }
  }
};

// src/modals/TemplateSelectorModal.ts
var import_obsidian2 = require("obsidian");
var TemplateSelectorModal = class extends import_obsidian2.Modal {
  templates;
  onChoose;
  constructor(app, templates, onChoose) {
    super(app);
    this.templates = templates;
    this.onChoose = onChoose;
  }
  onOpen() {
    this.contentEl.empty();
    this.contentEl.createEl("h2", { text: "Choose Template" });
    const templateList = this.contentEl.createEl("div", {
      cls: "template-list"
    });
    this.templates.forEach((template) => {
      const templateItem = templateList.createEl("div", {
        cls: "template-item",
        text: template.basename
      });
      templateItem.onclick = () => {
        this.onChoose(template);
        this.close();
      };
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/modals/FileNameModal.ts
var import_obsidian3 = require("obsidian");
var FileNameModal = class extends import_obsidian3.Modal {
  resolvePromise = () => void 0;
  result = "";
  constructor(app) {
    super(app);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438" });
    const setting = new import_obsidian3.Setting(contentEl).setName("\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 (\u0431\u0435\u0437 .md)").addText((text) => {
      text.onChange((value) => {
        this.result = value.trim();
      });
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          e.preventDefault();
          this.resolvePromise(this.result);
          this.close();
        }
      });
      window.setTimeout(() => text.inputEl.focus(), 10);
    });
    new import_obsidian3.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("\u0421\u043E\u0437\u0434\u0430\u0442\u044C").setCta().onClick(() => {
        this.resolvePromise(this.result);
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("\u041E\u0442\u043C\u0435\u043D\u0430").onClick(() => {
        this.resolvePromise(null);
        this.close();
      })
    );
  }
  async openAndWait() {
    return new Promise((resolve) => {
      this.resolvePromise = resolve;
      this.open();
    });
  }
  onClose() {
    this.contentEl.empty();
    if (this.resolvePromise) {
      this.resolvePromise(null);
    }
  }
};

// src/FactorySettingsTab.ts
var import_obsidian4 = require("obsidian");
var DEFAULT_SETTINGS = {
  templatesFolder: "Templates",
  defaultTemplate: "",
  upFieldName: "up",
  showRecentBadges: true,
  recentBadgesDays: 7,
  childNotesFolder: "O/_Pool"
  // <-- Дефолтное значение
};
var FactorySettingTab = class extends import_obsidian4.PluginSettingTab {
  plugin;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 \u0434\u043E\u0447\u0435\u0440\u043D\u0438\u0445 \u0437\u0430\u043C\u0435\u0442\u043E\u043A" });
    new import_obsidian4.Setting(containerEl).setName("\u041F\u0430\u043F\u043A\u0430 \u0441 \u0442\u0435\u043C\u043F\u043B\u0435\u0439\u0442\u0430\u043C\u0438").setDesc("\u041F\u0443\u0442\u044C \u043A \u043F\u0430\u043F\u043A\u0435 \u0441 \u0442\u0435\u043C\u043F\u043B\u0435\u0439\u0442\u0430\u043C\u0438").addText(
      (text) => text.setPlaceholder("Templates").setValue(this.plugin.settings.templatesFolder).onChange(async (value) => {
        this.plugin.settings.templatesFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("\u041F\u0430\u043F\u043A\u0430 \u0434\u043B\u044F \u043D\u043E\u0432\u044B\u0445 \u0437\u0430\u043C\u0435\u0442\u043E\u043A").setDesc("\u041F\u0443\u0442\u044C \u043A \u043F\u0430\u043F\u043A\u0435, \u043A\u0443\u0434\u0430 \u0431\u0443\u0434\u0443\u0442 \u0441\u043E\u0445\u0440\u0430\u043D\u044F\u0442\u044C\u0441\u044F \u0434\u043E\u0447\u0435\u0440\u043D\u0438\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438").addText(
      (text) => text.setPlaceholder("O/_Pool").setValue(this.plugin.settings.childNotesFolder).onChange(async (value) => {
        this.plugin.settings.childNotesFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u043F\u043E\u043B\u044F \u0441\u0432\u044F\u0437\u0438").setDesc(
      "\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u043F\u043E\u043B\u044F \u0434\u043B\u044F \u0441\u0441\u044B\u043B\u043A\u0438 \u043D\u0430 \u0440\u043E\u0434\u0438\u0442\u0435\u043B\u044C\u0441\u043A\u0443\u044E \u0437\u0430\u043C\u0435\u0442\u043A\u0443 \u0432 frontmatter"
    ).addText(
      (text) => text.setPlaceholder("up").setValue(this.plugin.settings.upFieldName).onChange(async (value) => {
        this.plugin.settings.upFieldName = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "\u041E\u0442\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435 \u043D\u0435\u0434\u0430\u0432\u043D\u0438\u0445 \u0444\u0430\u0439\u043B\u043E\u0432" });
    new import_obsidian4.Setting(containerEl).setName("\u041F\u043E\u043A\u0430\u0437\u044B\u0432\u0430\u0442\u044C \u0431\u0435\u0439\u0434\u0436\u0438 \u043D\u0435\u0434\u0430\u0432\u043D\u0438\u0445 \u0444\u0430\u0439\u043B\u043E\u0432").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showRecentBadges).onChange(async (value) => {
        this.plugin.settings.showRecentBadges = value;
        await this.plugin.saveSettings();
        this.plugin.updateRecentBadges();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("\u041A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u0434\u043D\u0435\u0439 \u0434\u043B\u044F \u0431\u0435\u0439\u0434\u0436\u0430").addText(
      (text) => text.setPlaceholder("7").setValue(this.plugin.settings.recentBadgesDays.toString()).onChange(async (value) => {
        const days = parseInt(value, 10);
        this.plugin.settings.recentBadgesDays = isNaN(days) ? 7 : days;
        await this.plugin.saveSettings();
        this.plugin.updateRecentBadges();
      })
    );
  }
};

// src/main.ts
var FactoryPlugin = class extends import_obsidian5.Plugin {
  settings = DEFAULT_SETTINGS;
  async onload() {
    await this.loadSettings();
    this.app.workspace.onLayoutReady(() => {
      this.updateRecentBadges();
    });
    this.registerEvent(
      this.app.vault.on("create", () => {
        this.updateRecentBadges();
      })
    );
    this.registerInterval(
      window.setInterval(
        () => {
          this.updateRecentBadges();
        },
        60 * 60 * 1e3
      )
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (isMarkdownFile(file)) {
          menu.addItem((item) => {
            item.setTitle("Create Child Note").setIcon("git-branch-plus").onClick(() => createChildNote(file, this));
          });
        }
        if (isDesktopCanvasFile(file)) {
          menu.addItem((item) => {
            item.setTitle("Clear Desktop").setIcon("square-x").onClick(() => clearCanvas(file, this.app));
          });
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (file) this.renderBreadcrumbs(file);
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
        if (activeView && activeView.file?.path === file.path) {
          this.renderBreadcrumbs(file);
        }
      })
    );
    this.addSettingTab(new FactorySettingTab(this.app, this));
  }
  onunload() {
    const badges = document.querySelectorAll(".factory-recent-badge");
    badges.forEach((badge) => badge.remove());
    const breadcrumbs = document.querySelectorAll(
      ".factory-breadcrumbs-container"
    );
    breadcrumbs.forEach((bc) => bc.remove());
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async renderBreadcrumbs(file) {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    if (!view) return;
    const existing = view.containerEl.querySelector(
      ".factory-breadcrumbs-container"
    );
    if (existing) existing.remove();
    const trail = await this.buildBreadcrumbTrail(file);
    if (trail.length <= 1) return;
    const bcContainer = document.createElement("div");
    bcContainer.addClass("factory-breadcrumbs-container");
    trail.forEach((item, index) => {
      const span = bcContainer.createEl("span", {
        text: item.basename,
        cls: "factory-breadcrumb-item"
      });
      if (item.file) {
        span.addClass("is-clickable");
        span.addEventListener("click", (e) => {
          e.preventDefault();
          this.app.workspace.getLeaf(false).openFile(item.file);
        });
      }
      if (index < trail.length - 1) {
        const sep = bcContainer.createEl("span", {
          cls: "factory-breadcrumb-separator"
        });
        (0, import_obsidian5.setIcon)(sep, "chevron-right");
      }
    });
    const viewContent = view.containerEl.querySelector(".view-content");
    if (viewContent) {
      viewContent.prepend(bcContainer);
    }
  }
  async buildBreadcrumbTrail(file) {
    const trail = [];
    let currentFile = file;
    const maxDepth = 15;
    let depth = 0;
    const visited = /* @__PURE__ */ new Set();
    while (currentFile && depth < maxDepth) {
      if (visited.has(currentFile.path)) {
        trail.push({ basename: "\u{1F504} \u0426\u0438\u043A\u043B", file: null });
        break;
      }
      visited.add(currentFile.path);
      trail.push({ basename: currentFile.basename, file: currentFile });
      const cache = this.app.metadataCache.getFileCache(currentFile);
      const upValue = cache?.frontmatter?.[this.settings.upFieldName];
      if (!upValue) break;
      const linkMatch = String(upValue).match(/\[\[(.*?)\]\]/);
      const parentLinkText = linkMatch ? linkMatch[1].split("|")[0] : String(upValue);
      const parentFile = this.app.metadataCache.getFirstLinkpathDest(
        parentLinkText,
        currentFile.path
      );
      currentFile = parentFile;
      depth++;
    }
    return trail.reverse();
  }
  updateRecentBadges() {
    const now = Date.now();
    const fileExplorers = this.app.workspace.getLeavesOfType("file-explorer");
    for (const leaf of fileExplorers) {
      const fileItems = Object.entries(leaf.view.fileItems);
      for (const [path, item] of fileItems) {
        const el = item.el;
        const existingBadge = el.querySelector(".factory-recent-badge");
        if (existingBadge) {
          existingBadge.remove();
        }
        if (!this.settings.showRecentBadges) {
          continue;
        }
        const file = item.file;
        if (!(file instanceof import_obsidian5.TFile) || file.extension !== "md" || path.startsWith(this.settings.templatesFolder)) {
          continue;
        }
        const diffTime = Math.abs(now - file.stat.ctime);
        const diffDays = Math.floor(diffTime / (1e3 * 60 * 60 * 24));
        if (diffDays <= this.settings.recentBadgesDays) {
          const titleInner = el.querySelector(".nav-file-title");
          if (titleInner) {
            const badge = document.createElement("span");
            badge.addClass("factory-recent-badge");
            badge.setAttribute("data-age", diffDays.toString());
            badge.setText(diffDays === 0 ? "new" : `${diffDays}d`);
            titleInner.appendChild(badge);
          }
        }
      }
    }
  }
};
function isMarkdownFile(file) {
  return file instanceof import_obsidian5.TFile && file.extension === "md";
}
function isDesktopCanvasFile(file) {
  return file instanceof import_obsidian5.TFile && file.path === "Desktop.canvas";
}
async function clearCanvas(canvasFile, app) {
  const modal = new PromiseConfirmModal(
    app,
    "Do you want to clear your Desktop?"
  );
  const confirmed = await modal.openAndWait();
  if (confirmed) {
    const emptyCanvas = {
      nodes: [],
      edges: []
    };
    await app.vault.modify(canvasFile, JSON.stringify(emptyCanvas, null, 2));
  }
}
async function createChildNote(parentFile, plugin) {
  const { app, settings } = plugin;
  const templateFolder = app.vault.getAbstractFileByPath(
    settings.templatesFolder
  );
  if (!(templateFolder instanceof import_obsidian5.TFolder)) {
    console.error("Template folder not found");
    return;
  }
  const templates = templateFolder.children.filter(
    (f) => f instanceof import_obsidian5.TFile && f.extension === "md"
  );
  const modal = new TemplateSelectorModal(
    app,
    templates,
    async (template) => {
      const nameModal = new FileNameModal(app);
      const inputName = await nameModal.openAndWait();
      if (!inputName) return;
      try {
        const rawContent = await app.vault.read(template);
        const content = rawContent.replace(/{{title}}/g, inputName).replace(/{{(?:date|time):?(.*?)}}/g, (_, format) => {
          return window.moment().format(format || "YYYY-MM-DD");
        });
        const targetFolderPath = settings.childNotesFolder || "";
        if (targetFolderPath) {
          const folderExists = app.vault.getAbstractFileByPath(targetFolderPath);
          if (!folderExists) {
            await app.vault.createFolder(targetFolderPath);
          }
        }
        const newFileName = `${inputName}.md`;
        let newFilePath = targetFolderPath ? `${targetFolderPath}/${newFileName}` : newFileName;
        let counter = 1;
        while (app.vault.getAbstractFileByPath(newFilePath)) {
          const incrementalName = `${inputName} (${counter}).md`;
          newFilePath = targetFolderPath ? `${targetFolderPath}/${incrementalName}` : incrementalName;
          counter++;
        }
        const newFile = await app.vault.create(newFilePath, content);
        await app.fileManager.processFrontMatter(
          newFile,
          (frontmatter) => {
            frontmatter[settings.upFieldName] = `[[${parentFile.basename}]]`;
          }
        );
        await app.workspace.getLeaf("tab").openFile(newFile);
      } catch (error) {
        console.error("Error creating child note:", error);
      }
    }
  );
  modal.open();
}
